### ISSUE TITLE
can you import this pushjet flow

### ISSUE THREAD

**Issue by djsuszi** [mrtnmtth/node-red-contrib-pushjet#1]
on node-red instance I can't install it automaticly
like for example
https://www.npmjs.com/package/node-red-contrib-hapcan

**Comment by mrtnmtth** [comment]
Originally I wanted to add some readme and documentation before publishing it. But I never got around doing so, because it just worked for me.

If I got some free time I may add at least a readme file and publish it to npm it this weekend.

You should also be able to install it manually with `cd .node-red/node_modules/` and `npm install git+https://git@github.com/mrtnmtth/node-red-contrib-pushjet.git`.

**Comment by mrtnmtth** [comment]
Just published the the node to [npm](https://www.npmjs.com/package/node-red-contrib-pushjet).  
It should be added to the [Node-RED Library](https://flows.nodered.org/) automatically soon.

Feedback is appreciated.
